### ISSUE TITLE
Serde Protobuf is broken in v3 release

### ISSUE THREAD

**Issue by str-dst** [redpanda-data/console#1721]
If used as described in the migration guide the serde protobuf settings result in an invalid configuration error during startup.

`{"level":"fatal","msg":"failed to load yaml config","error":"failed to validate YAML config (strict validation): decoding failed due to the following error(s):\n\n'serde.protobuf' has invalid keys: enabled, mappings"}`

The config migration tool also does not properly migrate the protobuf settings from the old v2 config.  
Instead it always generates an empty serde: {} stanza.

**Comment by JakeSCahill** [comment]
Hi @str-dst , thanks for the report.

I've fixed the issue in the migration tool here: https://github.com/redpanda-data/docs-ui/pull/278

Regarding the error in Console at startup, I believe that is due to missing `yaml:` tags:

```go
// Proto has all configuration options for decoding proto-serialized Kafka records.
type Proto struct {
	Enabled bool `json:"enabled"`

	// The required proto definitions can be provided via SchemaRegistry, Git or Filesystem
	Git        Git        `json:"git"`
	FileSystem Filesystem `json:"fileSystem"`

	// Mappings define what proto types shall be used for each Kafka topic. If SchemaRegistry is used, no mappings are required.
	Mappings []ProtoTopicMapping `json:"mappings"`

	// Proto import paths. By default, the baseDir/root is used. Set import paths
	// if multiple import paths relative to the baseDir shall be used. The
	// behavior is similar to the `-I` flag of protoc.
	ImportPaths []string `json:"importPaths"`
}
```

Because there’s no yaml:"enabled" tag, the YAML decoder doesn’t expect an enabled key in that section, and it flags it as an invalid key.

https://github.com/redpanda-data/console/blob/28673736e2c138ec51c8792ca7237f4cf39d602b/backend/pkg/config/proto.go#L19

**Comment by kewitschka** [comment]
The error still occurs, even with new v3 configuration.

**Comment by kewitschka** [comment]
The error `decoding failed due to the following error(s):\n\n'serde.protobuf' has invalid keys: enabled, git, importPaths, mappings"}`  still occurs, even with new v3 configuration.
```
      serde:
        protobuf:
          enabled: true
          mappings:
            - topicName: test
              valueProtoType: Test
          importPaths: [ "/src/main/proto" ]
          git:
            enabled: true
            refreshInterval: 5m
            repository:
              url: https://gitlab.com/protobuf.git
            basicAuth:
              enabled: true
              username: token 
```

Thanks!

**Comment by weeco** [comment]
@kewitschka Please make sure to use v3.0.1 or higher (e.g. v3.1.0 is already released). There was a bug with the config properties for the protobuf config.

**Comment by kewitschka** [comment]
@weeco Thank you very much. Is it possible that the version 3.1.0 has not yet been released as helm chart?
