### ISSUE TITLE
Feature Request: adding, updating and deleting schemas in the Schema Registry

### ISSUE THREAD

**Issue by sap1ens** [redpanda-data/console#434]
Currently, the Schema Registry is read-only. It'd be great to allow creating, updating and deleting schemas.

**Comment by sap1ens** [comment]
I guess it's a partial duplicate of https://github.com/redpanda-data/console/issues/206

**Comment by michaelandrepearce** [comment]
+1

**Comment by renanpablocruz** [comment]
+1

**Comment by twmb** [comment]
Done, coming out in next release

**Comment by MostlyAmiable** [comment]
@twmb Is this feature gated behind something? I just updated my Console version to v2.3.9 and I still don't see any CRUD options on the schema registry list page or the individual schema pages. Sorry if I'm missing something obvious.

**Comment by weeco** [comment]
@MostlyAmiable , this will land in the next feature release after @twmb 's comment which boils down to v2.4 which I'm going to cut within the next 2 days
