### ISSUE TITLE
redpanda-console_2.2.0_amd64.deb - incompatible with GLIBC_2.31

### ISSUE THREAD

**Issue by rnz** [redpanda-data/console#637]
In Debian 11 version of GLIBC is still 2.31:
```
# apt-cache policy libc6
libc6:
  Installed: 2.31-13+deb11u5
  Candidate: 2.31-13+deb11u5
  Version table:
 *** 2.31-13+deb11u5 500
        500 http://ftp.debian.org/debian bullseye/main amd64 Packages
        500 http://ftp.debian.org/debian bullseye-updates/main amd64 Packages
        100 /var/lib/dpkg/status
```

```
[redpanda-console_2.2.0_amd64.deb](https://github.com/redpanda-data/console/releases/download/v2.2.0/redpanda-console_2.2.0_amd64.deb)
```
```
redpanda-console[9702]: /usr/bin/redpanda-console: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/bin/redpanda-console)
redpanda-console[9702]: /usr/bin/redpanda-console: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/redpanda-console)
```

**Comment by weeco** [comment]
Hey @rnz ,
I'm clueless why libc should be included at all since we compile with CGO_ENABLED=0 . I updated a bunch of dependencies for the latest release - including Go itself to v1.20.1. Could you test whether the issues is gone?

Release:
https://github.com/redpanda-data/console/releases/tag/v2.2.2

**Comment by weeco** [comment]
Closing this as another user who was facing this issue reported that it got resolved with v2.2.2.

**Comment by thrashwerk** [comment]
I'm still getting the same error with v2.2.2 on Debian 11 (all updates installed and rebooted).

**Comment by thrashwerk** [comment]
@weeco Are you sure it's being built with CGO_ENABLED=0?

I didn't find any mention of CGO in the repo and only found it in one of the CI lint jobs where actions/setup-go had CGO_ENABLED=1.

**Comment by weeco** [comment]
Yes I'm sure. The build is happening outside this project as it includes the closed-source enterprise bits. However you can build the open source version on your own and give that a shot too.

We use Go releaser and as far as I know it's not possible out of the box to build it with CGO enabled. I'm sorry I can't be more helpful than that, but I have no clue why it would require libc to be honest.

**Comment by thrashwerk** [comment]
Built `backend/cmd/api` with `CGO_ENABLED=0 go build .` using Go 1.20.2 and there's no glibc errors.

**Comment by thrashwerk** [comment]
Downloaded GoReleaser 1.16.1. 

Built the package with `goreleaser build --single-target` = glibc errors.

Built the package with `CGO_ENABLED=0 goreleaser build --single-target` = no errors.

GoReleaser may not support building code that actually uses C but it doesn't mean that it completely disables cgo.

**Comment by weeco** [comment]
Hey @thrashwerk and @rnz , do you mind testing this release and see if it is fixed: https://github.com/redpanda-data/console/releases/tag/v2.2.3 ?

Sorry it took a bit longer than I hoped it would take.

**Comment by thrashwerk** [comment]
Updated to v2.2.3 on a Debian 11 system and can confirm it works now. Thanks @weeco!

**Comment by weeco** [comment]
Thank you @thrashwerk !
